## 1. Create a vector with values ranging from 3 to 20

In [ ]:
import numpy as np
empty_list = []
for i in range(3,20):
  empty_list.append(i)
a = np.array(empty_list)
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 2. Create a 3x3 identity matrix

In [ ]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 3. Create a random vector of size 10 and sort it

In [ ]:
import random
a = np.random.uniform(low = 0, high = 10, size=(1, 10))
a.sort(axis = -1)
print(a)

[[0.48228126 1.82082867 2.82370215 4.21253293 5.09365221 5.43080318
  5.77096006 6.38539671 7.32443747 8.33353295]]


## 4. Create a random 1-D matrix, Convert 1-D to 3-D matrix 

In [ ]:
a = np.random.uniform(low = 0, high = 5, size=(1,9))
a.reshape(3,3)
print(a.reshape(3,3))

[[4.20154212 0.65842481 1.85005042]
 [4.28416479 2.43561109 1.3444207 ]
 [1.49756806 2.40508219 1.87122293]]


# 5. Create 2 numpy arrays as matrices (random) , Print the result of multiplying the 2 matrices (as a numpy array)

In [ ]:
a = np.random.uniform(low= 1, high=5, size=(3,3))
b = np.random.uniform(10, 20, (3,2))
c = a.dot(b)
print(type(c))

<class 'numpy.ndarray'>


## 6. Create a 5*5 matrix (random ) , print the first three rows and first 2 columns

In [ ]:
a = np.random.uniform(1, 10, (5,5))
print(a)
print("The first three rows", a[0], a[1], a[2])
print("The first 2 columns", a[0][0], a[0][1], a[0][2], a[0][3], a[0][4],"\n\t\t", a[1][0], a[1][1], a[1][2], a[1][3], a[1][4])

[[5.74565544 9.05576616 9.3801189  4.03135734 6.36512769]
 [7.30389287 1.50454749 8.09932796 6.81286037 1.75859207]
 [9.43809598 6.23331452 5.74059559 7.97566071 1.38406458]
 [8.91962053 3.14808287 7.61262444 8.78004981 8.40842087]
 [5.28419404 7.32737684 1.0668657  3.9474371  9.10056693]]
The first three rows [5.74565544 9.05576616 9.3801189  4.03135734 6.36512769] [7.30389287 1.50454749 8.09932796 6.81286037 1.75859207] [9.43809598 6.23331452 5.74059559 7.97566071 1.38406458]
The first 2 columns 5.74565543882711 9.055766163907734 9.380118896214798 4.0313573395871725 6.365127693798985 
		 7.303892873011924 1.5045474936223218 8.099327955058701 6.812860371695688 1.7585920660941254


## 7. Create a 5*10 matrix , print subtract the mean of each row of a matrix

In [ ]:
a = np.random.uniform(1, 10, (5,10))
b = a - a.mean(axis = 1, keepdims= True)
print(b)

[[-1.19862867  1.40081548 -1.06750052  0.02249246 -3.70823912 -3.05431448
  -3.23750498  5.0653652   5.01873973  0.75877491]
 [-2.05192885 -0.83550898  3.45420294  1.55066373 -0.49518328 -2.65294884
  -1.03691015  3.15860514 -3.63263319  2.54164149]
 [-1.65192222 -1.04693164  0.20965686  0.19433564  0.10499022 -2.27615896
   1.73203645  0.32807384  3.00800389 -0.60208408]
 [-1.40356591  0.98661756  0.66634186 -2.80268715  1.2325393   2.24774876
   1.41544626  1.23101684 -2.49059113 -1.08286639]
 [ 3.77295067 -0.33755304  4.52744186 -2.22432    -1.1655759   3.09787978
  -3.19752603 -4.21837755 -0.71042161  0.45550181]]


# 8. Create random vector of size 10 and replace the minimum value by 100000

In [ ]:
a = np.random.uniform(low = 0, high = 10, size=(1, 10))
print(a)
print(a.min())
b = np.where(a == a.min(), 100000, a)
print(b)

[[8.22411386 1.35246866 7.85243562 0.47035658 8.78826162 1.34549258
  1.64630976 2.72114084 6.69811746 7.71764218]]
0.4703565829256129
[[8.22411386e+00 1.35246866e+00 7.85243562e+00 1.00000000e+05
  8.78826162e+00 1.34549258e+00 1.64630976e+00 2.72114084e+00
  6.69811746e+00 7.71764218e+00]]


## 9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)? 

In [ ]:
A = np.ones((4,4,3))
B = 2*np.ones((4,4))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#10.  Normalize an array below so the values range exactly between 0 and 1

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
a = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(a, min(a), max(a))
print((a - min(a))/(max(a)-min(a)))

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9] 4.3 7.9
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.1